### PR TITLE
Introducing new brand colors

### PR DESCRIPTION
**Pull request by thefoxis**
## Description

* updates `seed-color-scheme`, `seed-color-scheme-helpscout` and `seed-helpscout-theme` with new brand colors
* updates `READMEs` accordingly
* changes configs for border, state and other defaults

## Notes and questions

* I've assumed `gold` for `warning` states and `pink` for `error`. Is that correct?
* The following colors have been marked as secondary: `gold, green, pink, lavender, indigo, whale tail`. Is that what we want?
* `grey` has been replaced with `ash`. Is that what we want, or should we use `charcoal` here?
* I directly mapped settings for borders and notifications (see the diff [starting here](https://github.com/helpscout/seed/compare/new-brand-colors?expand=1#diff-f714d28da52acea69a0e852406669e7cR200)), but I think those colors don't work that well together so I'd suggest swapping the `200|500|800` color combo to `50|300|800` (see pictured below). Any thoughts here?

seed-notifications-update

## Reviewers
@ItsJonQ @jaredmcdaniel

### CODE REVIEW

**Comment by jaredmcdaniel** [comment]
Thank you @thefoxis and @q!

1) Yes, correct!
2) Yes.
3) Grey == Ash
4) **Error** is still feeling a little light IMO. Could we try darkening the text and border color one shade to compare?

**Comment by thefoxis** [comment]
thanks for stepping in @ItsJonQ! I have two questions:

1) would you be able to point me to all the files / packages that should be modified to address the notification style? I'm assuming it's the config I've already touched and potentially `seed-states`?
2) after that's done, is this ready for release, you think? are we going to retire all `seed-*` repositories and upgrade to this package w/monorepo?

@jaredmcdaniel got it :+1: will update!

**Comment by ItsJonQ** [comment]
@thefoxis Amazing questions!

1. At the moment, the state colors can come from `seed-state` or `seed-color-scheme`.
For context, `seed-color-scheme` was enhanced (a year ago?) to include other colours in additional to the palette (like brand, ui, borders, and states).

If you use `seed-state`, you'll need to do something like this to get the color value:

```scss
_get($seed-states-colors, warning, background-color);
```

(The `_get` function comes from `seed-dash`)

 With `seed-color-scheme`, it's simply:

```scss
_color(state, warning, background-color)
```

I'm not sure what how the notification UI is rendered within the application. Hopefully the above examples will help! (Use `_color()`. It's easier, haha).

2. I believe it should be ready for release, yes!

I did a lot of testing yesterday to see how the new Seed (aka. monorepo Seed) will integrate with existing systems. To my surprise... it's literally a drop-in replacement. Just change the `package.json` key/values from `seed-state` -> `@seedcss/seed-state`.

The tools I built to automatically find/consolidate Sass dependencies can handle this (I was shocked to be honest. Very happy though).

As a test, I've actually updated all the seed packs in [Blue](https://github.com/helpscout/blue) to use monorepo Seed. It works great!

As a bonus test... I even added the Blue+MonoSeed version into the application as a dependency. No conflicts.

Based on ☝️ examples... I feel like we can make the shift, when we're ready.

Once we do, yes, we shall retire the singular/stray `seed-*` repos, and use the 🤘 monorepo 🤘

**Comment by ItsJonQ** [comment]
@thefoxis Moarrr things.

I've done a lot of updates to this repo (as you see from the ☝️ timeline). One thing I added very recently was Storybook for development and testing.

screen shot 2018-10-16 at 10 32 51 am

Above is a screenshot for a quick Story I put together for `seed-alert`, to check out the values.

I recommend using this for development. My previous (ancient) method was to compile the CSS and do it within an `.html` file, haha.

The Storybook supports live reloading. Changes made to dependencies also recompile + reload.

For the example of `seed-alert`, I can change values in `seed-states` or even `seed-color-scheme`, and it'll reload with the new value (very neat!).

**Comment by thefoxis** [comment]
@ItsJonQ wow, awesome work! :clap: super helpful to have the preview, I've been wondering what's the best way of checking the changes I've been making.

@jaredmcdaniel I've updated `seed-states` and the `seed-color-scheme` as you requested:

screen shot 2018-10-17 at 10 52 48 am

let me know if you think that's right (you can run it locally if you pull, `npm i` and then `npm run storybook`. it's available at `http://localhost:7200`)! I'm pairing with @ItsJonQ tomorrow morning on this, in hopes to release a new version so we can push the `hs-marketing` side of the task :+1:

**Comment by jaredmcdaniel** [comment]
@thefoxis this is great! Just pushed a small CANI to error notifications.

I also just 🍐 with @ItsJonQ and he showed me the ropes with everything. Some things I'd like to confirm:

1) Though the alert notifications are looking good now, is there a specific reason we're focused on them? I just want to confirm that we don't flip the switch with any color changes in the app until we're able to do a complete audit throughout ... which I'm guessing is going to be a fairly extensive effort. I'm just concerned with `hs-marketing` at this point. Pretty sure we're all on the same page, but just wanted to mention again. 😄 

2) Grey vs Ash. I'm wondering ... would it save us a ton of time to just call `Ash` `Grey` and simply update the hexes? Ash is definitely a cooler name but I'm just not sure its worth the tradeoff at this point. I'm okay with `Gold` since I think the current usage of `Yellow` is much more minimal. Thoughts?

**Comment by thefoxis** [comment]
@jaredmcdaniel 

1) with the alerts, I just wanted to ensure that they look alright in case the defaults are used anywhere without any modifications, that's all! but it won't be updated in the app unless someone manually switches from seed packs to monorepo (this repository), so we don't have to worry about the changes magically making it in 😄 happy to ship with what we have!

2) no problem with the name change at all! it's pretty straightforward to swap words in VSCode and it allows granular review of what you're accepting (similarly to Github) so I'd say we can definitely proceed with `Ash` :+1: (it'd be a bit of work in the `hs-app`, but nothing too major)

**Comment by ItsJonQ** [comment]
@thefoxis Strange that you couldn't publish! I just checked.. I did `npm owner ls` in one of the seed packages, and you show up as an owner.

Published another alpha version for you! We'll hop on a call tomorrow and get this resolved 🙌

**Comment by ItsJonQ** [comment]
@thefoxis 🙌 🚀 for merge and release!~!

**Pull request merged**
